"""
PDF report generator — Análisis de Riesgos por Tramo de Ruta.
Landscape Letter, one section per tramo: header + map + PROCESO table + OS profile.
Uses reportlab. Map images are generated by map_generator.get_segment_map().
"""

import io
import os
import logging
from datetime import datetime

from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, HRFlowable, KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable

from producto.map_generator import get_segment_map

logger = logging.getLogger(__name__)

# ── Palette ────────────────────────────────────────────────────────────────────
NAVY    = colors.HexColor('#1a1a2e')
PURPLE  = colors.HexColor('#6d28d9')
RED_ACC = colors.HexColor('#e63946')
LIGHT_B = colors.HexColor('#eff6ff')
LIGHT_G = colors.HexColor('#f0fdf4')
STRIPE  = colors.HexColor('#f0f4f8')
GREY    = colors.HexColor('#9ca3af')
WHITE   = colors.white

# ── Column widths for the 7-column PROCESO table (landscape Letter ~10 in usable) ──
COL_WIDTHS = [
    0.28 * inch,   # #
    1.15 * inch,   # Área
    1.45 * inch,   # Dinámica
    1.55 * inch,   # Amenazas
    1.55 * inch,   # Vigilancia
    1.45 * inch,   # Restricción
    1.55 * inch,   # Intervención
]

HEADERS = ['#', 'Área', 'Dinámica', 'Amenazas', 'Vigilancia', 'Restricción', 'Intervención']


def _styles():
    base = getSampleStyleSheet()
    cell = ParagraphStyle(
        'Cell',
        fontName='Helvetica',
        fontSize=6.5,
        leading=8.5,
        spaceAfter=0,
        spaceBefore=0,
        wordWrap='CJK',
    )
    header_cell = ParagraphStyle(
        'HeaderCell',
        fontName='Helvetica-Bold',
        fontSize=7,
        leading=9,
        textColor=WHITE,
    )
    caption = ParagraphStyle(
        'Caption',
        fontName='Helvetica-Oblique',
        fontSize=7.5,
        textColor=GREY,
        spaceAfter=4,
    )
    os_note = ParagraphStyle(
        'OSNote',
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#374151'),
        spaceAfter=6,
    )
    return base, cell, header_cell, caption, os_note


def _wrap(text, style):
    """Wrap a string in a Paragraph so reportlab can word-wrap inside table cells."""
    return Paragraph(str(text), style)


def _build_proceso_table(tabla_rows, cell_style, header_style):
    """Build the 7-column PROCESO Table flowable."""
    header_para = [_wrap(h, header_style) for h in HEADERS]
    data = [header_para]
    for i, row in enumerate(tabla_rows):
        data.append([_wrap(cell, cell_style) for cell in row])

    t = Table(data, colWidths=COL_WIDTHS, repeatRows=1)
    t.setStyle(TableStyle([
        # Header row
        ('BACKGROUND',   (0, 0), (-1, 0),  NAVY),
        ('TEXTCOLOR',    (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',     (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',     (0, 0), (-1, 0),  7),
        ('BOTTOMPADDING',(0, 0), (-1, 0),  5),
        ('TOPPADDING',   (0, 0), (-1, 0),  5),
        # Alternating row background
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, STRIPE]),
        # Grid
        ('GRID',         (0, 0), (-1, -1), 0.4, GREY),
        # Vertical alignment
        ('VALIGN',       (0, 0), (-1, -1), 'TOP'),
        # Padding
        ('LEFTPADDING',  (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ('TOPPADDING',   (0, 1), (-1, -1), 4),
        ('BOTTOMPADDING',(0, 1), (-1, -1), 4),
        # # column centred
        ('ALIGN',        (0, 0), (0, -1),  'CENTER'),
        ('FONTNAME',     (0, 1), (0, -1),  'Helvetica-Bold'),
        ('FONTSIZE',     (0, 1), (0, -1),  7),
    ]))
    return t


def _load_state_color(load_state):
    return LIGHT_B if load_state == 'Carga Completa' else colors.HexColor('#faf5ff')


def build_pdf(tramos: list, route_label: str = '') -> bytes:
    """
    Build the full PDF report in memory and return the raw bytes.

    tramos: the list of tramo dicts as returned by segment_route().
            Each tramo must have:
              posicion_inicial, posicion_final, trazo_topografia,
              distancia_km, risk_analysis (with load_state, tabla_proceso, os_profile).
    route_label: optional human-readable route string for the cover page.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        rightMargin=0.4 * inch,
        leftMargin=0.4 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.35 * inch,
    )

    base_styles, cell_style, header_style, caption_style, os_style = _styles()
    story = []

    # ── COVER PAGE ─────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.8 * inch))
    story.append(Paragraph(
        'ANÁLISIS DE RIESGOS POR TRAMO DE RUTA',
        ParagraphStyle('Cover', fontName='Helvetica-Bold', fontSize=22, leading=28,
                       textColor=NAVY, spaceAfter=16, alignment=1),
    ))
    story.append(HRFlowable(width='100%', thickness=2, color=PURPLE, spaceAfter=14))

    meta = [
        ('Vehículo',      'Camión de doble remolque'),
        ('Dinámica de carga', 'Sale con carga completa · Entrega 50 % en primer destino · Continúa con media carga'),
        ('Ruta',          route_label or 'No especificada'),
        ('Total de tramos', str(len(tramos))),
        ('Fecha de generación', datetime.now().strftime('%d/%m/%Y %H:%M')),
    ]
    for label, value in meta:
        story.append(Paragraph(
            f'<b>{label}:</b>  {value}',
            ParagraphStyle('MetaLine', fontName='Helvetica', fontSize=11, leading=16,
                           textColor=colors.HexColor('#374151'), spaceBefore=4),
        ))

    story.append(PageBreak())

    # ── PER-TRAMO PAGES ────────────────────────────────────────────────────────
    for tramo in tramos:
        num   = tramo.get('numero', '?')
        pi    = tramo.get('posicion_inicial', {})
        pf    = tramo.get('posicion_final',   {})
        trazo = tramo.get('trazo_topografia', '')
        dist  = tramo.get('distancia_km', 0)
        ra    = tramo.get('risk_analysis', {})

        load_state    = ra.get('load_state', 'Carga Completa')
        load_flag     = ra.get('load_state_flag', False)
        tabla_proceso = ra.get('tabla_proceso', [])
        os_profile    = ra.get('os_profile', '')

        start_coords = (pi.get('lat', 0), pi.get('lon', 0))
        end_coords   = (pf.get('lat', 0), pf.get('lon', 0))
        seg_label    = f'Tramo {num}'

        # ── Segment header ─────────────────────────────────────────────────────
        lc = _load_state_color(load_state)

        header_content = [
            [
                Paragraph(f'TRAMO {num}', ParagraphStyle(
                    'TN', fontName='Helvetica-Bold', fontSize=13, textColor=PURPLE)),
                Paragraph(f'{trazo}', ParagraphStyle(
                    'TT', fontName='Helvetica', fontSize=10, textColor=colors.HexColor('#374151'))),
                Paragraph(f'Distancia: <b>{dist:.1f} km</b>', ParagraphStyle(
                    'TD', fontName='Helvetica', fontSize=9, textColor=colors.HexColor('#374151'))),
                Paragraph(
                    f'<b>{load_state}</b>' + ('  ⚠ Perfil modificado por media carga' if load_flag else ''),
                    ParagraphStyle('TL', fontName='Helvetica-Bold', fontSize=9,
                                   textColor=RED_ACC if load_flag else PURPLE)),
            ]
        ]
        header_table = Table(header_content, colWidths=[1.4*inch, 2.5*inch, 1.7*inch, 3.8*inch])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), lc),
            ('BOX',        (0, 0), (-1, -1), 1, PURPLE),
            ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING',(0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING',(0, 0),(-1,-1), 7),
        ]))
        story.append(KeepTogether([header_table]))
        story.append(Spacer(1, 0.12 * inch))

        # Coordinates line
        story.append(Paragraph(
            f'Inicio: <b>{pi.get("lat", 0):.5f}°N, {pi.get("lon", 0):.5f}°O</b>  →  '
            f'Fin: <b>{pf.get("lat", 0):.5f}°N, {pf.get("lon", 0):.5f}°O</b>',
            ParagraphStyle('Coords', fontName='Helvetica', fontSize=8,
                           textColor=colors.HexColor('#6b7280'), spaceAfter=8),
        ))

        # ── Map image ─────────────────────────────────────────────────────────
        try:
            map_path = get_segment_map(start_coords, end_coords, seg_label)
            if os.path.exists(map_path) and os.path.getsize(map_path) > 0:
                story.append(Image(map_path, width=6.8 * inch, height=2.8 * inch))
                story.append(Paragraph(
                    f'Mapa del {seg_label} — ruta destacada en rojo · '
                    f'Marcador verde = punto de inicio · Marcador rojo = punto final',
                    caption_style,
                ))
        except Exception as e:
            logger.warning("Map generation failed for tramo %s: %s", num, e)
            story.append(Paragraph(
                f'[Mapa no disponible para {seg_label}]',
                caption_style,
            ))

        story.append(Spacer(1, 0.1 * inch))

        # ── PROCESO table ──────────────────────────────────────────────────────
        story.append(Paragraph(
            'ANÁLISIS DE RIESGOS OPERATIVOS — PROCESO',
            ParagraphStyle('PH', fontName='Helvetica-Bold', fontSize=9,
                           textColor=NAVY, spaceAfter=5),
        ))

        if tabla_proceso:
            story.append(_build_proceso_table(tabla_proceso, cell_style, header_style))
        else:
            story.append(Paragraph('(Sin datos de análisis disponibles)', caption_style))

        story.append(Spacer(1, 0.1 * inch))

        # ── OS Profile ─────────────────────────────────────────────────────────
        story.append(HRFlowable(width='100%', thickness=0.8, color=PURPLE, spaceAfter=6))
        story.append(Paragraph(
            'PERFIL DEL OFICIAL DE SEGURIDAD (OS):',
            ParagraphStyle('OSH', fontName='Helvetica-Bold', fontSize=8,
                           textColor=PURPLE, spaceAfter=3),
        ))
        story.append(Paragraph(os_profile, os_style))

        story.append(PageBreak())

    doc.build(story)
    return buffer.getvalue()
