"""
PDF report generator — Resumen por Estado.
Landscape Letter, grouped by state:
  cover → overview map → one section per state
    (state header + segment map + PROCESO summary table + emergency contacts).
Uses reportlab. Map images generated by map_generator.get_segment_map().
"""

import io
import os
import logging
from collections import Counter
from datetime import datetime

from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, HRFlowable, KeepTogether,
)

from producto.map_generator import get_segment_map
from producto.pdf_generator import (
    _build_emergency_table, _load_state_color, _styles, _wrap,
    NAVY, PURPLE, EMRG_RED, GREY, WHITE, STRIPE,
)

logger = logging.getLogger(__name__)

# 3-column summary PROCESO table (same total width as emergency table: 8.98")
SUMMARY_HEADERS    = ['Área', 'Nivel de Riesgo / Vigilancia', 'Intervención']
SUMMARY_COL_WIDTHS = [1.5 * inch, 5.48 * inch, 2.0 * inch]


# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _group_by_state(tramos: list) -> list:
    """Group consecutive tramos by emergency_contacts.estado."""
    groups = []
    for tramo in tramos:
        ec    = tramo.get('emergency_contacts') or {}
        state = ec.get('estado') or 'Desconocido'
        if groups and groups[-1]['state'] == state:
            groups[-1]['tramos'].append(tramo)
        else:
            groups.append({'state': state, 'tramos': [tramo]})
    return groups


def _merge_proceso_rows(all_tablas: list) -> list:
    """
    Collapse multiple tabla_proceso lists (each 6 rows × 7 cols) into one
    summary list of [Área, Vigilancia, Intervención] rows.
    For each row index, pick the candidate with the richest Vigilancia text.
    """
    if not all_tablas:
        return []
    n_rows = max(len(t) for t in all_tablas)
    result = []
    for row_idx in range(n_rows):
        candidates = [t[row_idx] for t in all_tablas if row_idx < len(t)]
        if not candidates:
            continue
        best = max(candidates, key=lambda r: len(str(r[4])) if len(r) > 4 else 0)
        result.append([
            best[1] if len(best) > 1 else '',   # Área
            best[4] if len(best) > 4 else '',   # Vigilancia → Nivel de Riesgo
            best[6] if len(best) > 6 else '',   # Intervención
        ])
    return result


def _merge_group(group: dict) -> dict:
    """Produce a merged state-level dict from a group of consecutive tramos."""
    tramos = group['tramos']
    first  = tramos[0]
    last   = tramos[-1]

    # Concatenate tramo_coords without duplicating join points
    all_coords = []
    for i, t in enumerate(tramos):
        coords = t.get('tramo_coords') or []
        all_coords.extend(coords if i == 0 else coords[1:])

    # Dominant topography
    trazos = [t.get('trazo_topografia', 'Recta') for t in tramos]
    dominant_trazo = Counter(trazos).most_common(1)[0][0]

    # Merge PROCESO tables
    all_tablas   = [t.get('risk_analysis', {}).get('tabla_proceso', []) for t in tramos]
    summary_rows = _merge_proceso_rows([tb for tb in all_tablas if tb])

    return {
        'state':           group['state'],
        'posicion_inicial': first.get('posicion_inicial', {}),
        'posicion_final':   last.get('posicion_final',   {}),
        'trazo_topografia': dominant_trazo,
        'distancia_km':     round(sum(t.get('distancia_km', 0) for t in tramos), 2),
        'tramo_coords':     all_coords,
        'emergency_contacts': first.get('emergency_contacts') or {},
        'load_state':       last.get('risk_analysis', {}).get('load_state', 'Carga Completa'),
        'summary_rows':     summary_rows,
        'tramo_count':      len(tramos),
    }


def _build_proceso_summary_table(summary_rows: list, cell_style, header_style):
    """Build the 3-column summary PROCESO Table flowable."""
    data = [[_wrap(h, header_style) for h in SUMMARY_HEADERS]]
    for row in summary_rows:
        data.append([_wrap(cell, cell_style) for cell in row])

    t = Table(data, colWidths=SUMMARY_COL_WIDTHS, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, 0),  NAVY),
        ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 0), (-1, 0),  7),
        ('BOTTOMPADDING', (0, 0), (-1, 0),  5),
        ('TOPPADDING',    (0, 0), (-1, 0),  5),
        ('ROWBACKGROUNDS',(0, 1), (-1, -1), [WHITE, STRIPE]),
        ('GRID',          (0, 0), (-1, -1), 0.4, GREY),
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING',   (0, 0), (-1, -1), 3),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 3),
        ('TOPPADDING',    (0, 1), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
    ]))
    return t


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def build_summary_pdf(tramos: list, route_label: str = '') -> bytes:
    """
    Build a summarized PDF report grouped by state and return raw bytes.

    tramos: the list of tramo dicts as returned by segment_route().
    route_label: optional human-readable route string for the cover page.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        rightMargin=0.4 * inch,
        leftMargin=0.4 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.35 * inch,
    )

    _, cell_style, header_style, caption_style, _ = _styles()
    story = []

    groups = _group_by_state(tramos)
    merged = [_merge_group(g) for g in groups]
    total_dist = round(sum(m['distancia_km'] for m in merged), 2)

    # ── Cover page ─────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.8 * inch))
    story.append(Paragraph(
        'ANÁLISIS DE RIESGOS — RESUMEN POR ESTADO',
        ParagraphStyle('Cover', fontName='Helvetica-Bold', fontSize=22, leading=28,
                       textColor=NAVY, spaceAfter=16, alignment=1),
    ))
    story.append(HRFlowable(width='100%', thickness=2, color=PURPLE, spaceAfter=14))
    for label, value in [
        ('Vehículo',            'Camión de doble remolque'),
        ('Dinámica de carga',   'Sale con carga completa · Entrega 50 % en primer destino · Continúa con media carga'),
        ('Ruta',                route_label or 'No especificada'),
        ('Total de tramos',     str(len(tramos))),
        ('Estados en ruta',     str(len(merged))),
        ('Distancia total',     f'{total_dist} km'),
        ('Fecha de generación', datetime.now().strftime('%d/%m/%Y %H:%M')),
    ]:
        story.append(Paragraph(
            f'<b>{label}:</b>  {value}',
            ParagraphStyle('MetaLine', fontName='Helvetica', fontSize=11, leading=16,
                           textColor=colors.HexColor('#374151'), spaceBefore=4),
        ))
    story.append(PageBreak())

    # ── Overview map (full route) ───────────────────────────────────────────
    if tramos:
        all_route_coords = []
        for i, t in enumerate(tramos):
            coords = t.get('tramo_coords') or []
            all_route_coords.extend(coords if i == 0 else coords[1:])

        first_tramo = tramos[0].get('posicion_inicial', {})
        last_tramo  = tramos[-1].get('posicion_final',  {})
        start = (first_tramo.get('lat', 0), first_tramo.get('lon', 0))
        end   = (last_tramo.get('lat', 0),  last_tramo.get('lon', 0))

        story.append(Paragraph(
            'MAPA GENERAL DE LA RUTA',
            ParagraphStyle('MH', fontName='Helvetica-Bold', fontSize=12,
                           textColor=NAVY, spaceAfter=8, alignment=1),
        ))
        story.append(HRFlowable(width='100%', thickness=1.5, color=PURPLE, spaceAfter=10))
        try:
            map_path = get_segment_map(
                start, end, 'Ruta Completa',
                route_coords=all_route_coords or None,
            )
            if os.path.exists(map_path) and os.path.getsize(map_path) > 0:
                story.append(Image(map_path, width=9.0 * inch, height=3.5 * inch))
                story.append(Paragraph(
                    'Ruta completa — marcador verde = origen · marcador rojo = destino final',
                    caption_style,
                ))
        except Exception as e:
            logger.warning("Overview map generation failed: %s", e)
            story.append(Paragraph('[Mapa general no disponible]', caption_style))
        story.append(PageBreak())

    # ── Per-state sections ──────────────────────────────────────────────────
    for idx, m in enumerate(merged):
        state       = m['state']
        pi          = m['posicion_inicial']
        pf          = m['posicion_final']
        trazo       = m['trazo_topografia']
        dist        = m['distancia_km']
        lc          = _load_state_color(m['load_state'])
        tramo_count = m['tramo_count']

        # State header band
        plural = 's' if tramo_count != 1 else ''
        header_content = [[
            Paragraph(state.upper(), ParagraphStyle(
                'SN', fontName='Helvetica-Bold', fontSize=13, textColor=PURPLE)),
            Paragraph(trazo, ParagraphStyle(
                'ST', fontName='Helvetica', fontSize=10,
                textColor=colors.HexColor('#374151'))),
            Paragraph(f'Distancia: <b>{dist:.1f} km</b>', ParagraphStyle(
                'SD', fontName='Helvetica', fontSize=9,
                textColor=colors.HexColor('#374151'))),
            Paragraph(f'<b>{tramo_count} tramo{plural} fusionado{plural}</b>', ParagraphStyle(
                'SC', fontName='Helvetica-Bold', fontSize=9, textColor=PURPLE)),
        ]]
        header_table = Table(header_content,
                             colWidths=[2.5 * inch, 2.5 * inch, 1.7 * inch, 2.7 * inch])
        header_table.setStyle(TableStyle([
            ('BACKGROUND',    (0, 0), (-1, -1), lc),
            ('BOX',           (0, 0), (-1, -1), 1,  PURPLE),
            ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING',   (0, 0), (-1, -1), 8),
            ('TOPPADDING',    (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ]))
        story.append(KeepTogether([header_table]))
        story.append(Spacer(1, 0.12 * inch))

        story.append(Paragraph(
            f'Inicio: <b>{pi.get("lat", 0):.5f}°N, {pi.get("lon", 0):.5f}°O</b>  →  '
            f'Fin: <b>{pf.get("lat", 0):.5f}°N, {pf.get("lon", 0):.5f}°O</b>',
            ParagraphStyle('Coords', fontName='Helvetica', fontSize=8,
                           textColor=colors.HexColor('#6b7280'), spaceAfter=8),
        ))

        # Segment map
        start_coords  = (pi.get('lat', 0), pi.get('lon', 0))
        end_coords_t  = (pf.get('lat', 0), pf.get('lon', 0))
        tramo_coords  = m.get('tramo_coords') or []
        try:
            map_path = get_segment_map(
                start_coords, end_coords_t, state,
                route_coords=tramo_coords or None,
            )
            if os.path.exists(map_path) and os.path.getsize(map_path) > 0:
                story.append(Image(map_path, width=6.8 * inch, height=2.8 * inch))
                story.append(Paragraph(
                    f'Segmento {state} — ruta real trazada en rojo · '
                    'marcador verde = inicio del segmento · marcador rojo = fin',
                    caption_style,
                ))
        except Exception as e:
            logger.warning("Map generation failed for state %s: %s", state, e)
            story.append(Paragraph(f'[Mapa no disponible para {state}]', caption_style))

        story.append(Spacer(1, 0.1 * inch))

        # Summary PROCESO table
        story.append(Paragraph(
            'RESUMEN DE RIESGOS OPERATIVOS — PROCESO',
            ParagraphStyle('PH', fontName='Helvetica-Bold', fontSize=9,
                           textColor=NAVY, spaceAfter=5),
        ))
        if m['summary_rows']:
            story.append(_build_proceso_summary_table(m['summary_rows'], cell_style, header_style))
        else:
            story.append(Paragraph('(Sin datos de análisis disponibles)', caption_style))

        story.append(Spacer(1, 0.1 * inch))

        # Emergency contacts
        ec = m['emergency_contacts']
        if ec:
            story.append(HRFlowable(width='100%', thickness=0.8, color=EMRG_RED, spaceAfter=6))
            estado_name = ec.get('estado', '')
            story.append(Paragraph(
                f'CONTACTOS DE EMERGENCIA{" — " + estado_name.upper() if estado_name else ""}:',
                ParagraphStyle('EmrgH', fontName='Helvetica-Bold', fontSize=8,
                               textColor=EMRG_RED, spaceAfter=4),
            ))
            emrg_table = _build_emergency_table(ec, cell_style)
            if emrg_table:
                story.append(emrg_table)

        if idx < len(merged) - 1:
            story.append(PageBreak())

    doc.build(story)
    return buffer.getvalue()
