"""
PDF report generator — Análisis de Riesgos por Tramo de Ruta.
Landscape Letter, one section per tramo:
  header + map (ruta real) + PROCESO table + OS profile + contactos de emergencia.
Uses reportlab. Map images are generated by map_generator.get_segment_map().
"""

import io
import os
import logging
from datetime import datetime

from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, HRFlowable, KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable

from producto.map_generator import get_segment_map

logger = logging.getLogger(__name__)

# ── Palette — Rojo vivo + Azul eléctrico ─────────────────────────────────────────────────────
NAVY     = colors.HexColor('#1e40af')   # deep blue  — table headers, cover title
PURPLE   = colors.HexColor('#2563eb')   # electric blue — borders, HR lines, headings
RED_ACC  = colors.HexColor('#ef4444')   # vivid red  — half-load warning
EMRG_RED = colors.HexColor('#dc2626')   # red dark   — emergency header bg / text
LIGHT_B  = colors.HexColor('#dbeafe')   # light blue — tramo header band (full load)
STRIPE   = colors.HexColor('#f0f4f8')
GREY     = colors.HexColor('#9ca3af')
WHITE    = colors.white

# ── PROCESO table column widths (landscape Letter ~10.2 in usable) ─────────────────
COL_WIDTHS = [
    0.28 * inch,   # #
    1.15 * inch,   # Área
    1.45 * inch,   # Dinámica
    1.55 * inch,   # Amenazas
    1.55 * inch,   # Vigilancia
    1.45 * inch,   # Restricción
    1.55 * inch,   # Intervención
]
HEADERS = ['#', 'Área', 'Dinámica', 'Amenazas', 'Vigilancia', 'Restricción', 'Intervención']

# ── Emergency contacts table config ───────────────────────────────────────────────
EMRG_CAT_LABELS = [
    ('ambulancia',        'Ambulancias / Cruz Roja', colors.HexColor('#fff1f2')),
    ('hospital',          'Hospitales',              colors.HexColor('#fefce8')),
    ('sedena',            'SEDENA / Ejército',       colors.HexColor('#dbeafe')),
    ('guardia_nacional',  'Guardia Nacional',        colors.HexColor('#f0fdf4')),
    ('policia_estatal',   'Policía Estatal (SSP)',   colors.HexColor('#faf5ff')),
    ('policia_municipal', 'Policía Municipal',       colors.HexColor('#fff7ed')),
    ('guardia_caminos',   'GN Carreteras / CAPUFE',  colors.HexColor('#f0fdfa')),
]
# Category (1.5") + Institution (5.98") + Phone (1.5") = 8.98" matches PROCESO width
EMRG_COL_WIDTHS = [1.5 * inch, 5.98 * inch, 1.5 * inch]


def _styles():
    base = getSampleStyleSheet()
    cell = ParagraphStyle(
        'Cell', fontName='Helvetica', fontSize=6.5, leading=8.5,
        spaceAfter=0, spaceBefore=0, wordWrap='CJK',
    )
    header_cell = ParagraphStyle(
        'HeaderCell', fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=WHITE,
    )
    caption = ParagraphStyle(
        'Caption', fontName='Helvetica-Oblique', fontSize=7.5, textColor=GREY, spaceAfter=4,
    )
    os_note = ParagraphStyle(
        'OSNote', fontName='Helvetica', fontSize=7.5, leading=10,
        textColor=colors.HexColor('#374151'), spaceAfter=6,
    )
    return base, cell, header_cell, caption, os_note


def _wrap(text, style):
    """Wrap a string in a Paragraph so reportlab can word-wrap inside table cells."""
    return Paragraph(str(text), style)


def _build_proceso_table(tabla_rows, cell_style, header_style):
    """Build the 7-column PROCESO Table flowable."""
    data = [[_wrap(h, header_style) for h in HEADERS]]
    for row in tabla_rows:
        data.append([_wrap(cell, cell_style) for cell in row])

    t = Table(data, colWidths=COL_WIDTHS, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, 0),  NAVY),
        ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 0), (-1, 0),  7),
        ('BOTTOMPADDING', (0, 0), (-1, 0),  5),
        ('TOPPADDING',    (0, 0), (-1, 0),  5),
        ('ROWBACKGROUNDS',(0, 1), (-1, -1), [WHITE, STRIPE]),
        ('GRID',          (0, 0), (-1, -1), 0.4, GREY),
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING',   (0, 0), (-1, -1), 3),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 3),
        ('TOPPADDING',    (0, 1), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
        ('ALIGN',         (0, 0), (0, -1),  'CENTER'),
        ('FONTNAME',      (0, 1), (0, -1),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 1), (0, -1),  7),
    ]))
    return t


def _build_emergency_table(emergency_contacts: dict, cell_style):
    """
    Build a compact 3-column emergency contacts table for a tramo.
    Rows are grouped by service category with merged category cells and
    colour-coded row bands.
    """
    if not emergency_contacts:
        return None

    hdr_style = ParagraphStyle(
        'EmrgHdr', fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=WHITE,
    )
    cat_style = ParagraphStyle(
        'EmrgCat', fontName='Helvetica-Bold', fontSize=6.5, leading=8.5,
        textColor=colors.HexColor('#1a1a2e'),
    )

    data = [[
        _wrap('Categoría', hdr_style),
        _wrap('Institución', hdr_style),
        _wrap('Teléfono', hdr_style),
    ]]
    style_cmds = [
        ('BACKGROUND',    (0, 0), (-1, 0),  EMRG_RED),
        ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 0), (-1, 0),  7),
        ('BOTTOMPADDING', (0, 0), (-1, 0),  5),
        ('TOPPADDING',    (0, 0), (-1, 0),  5),
        ('GRID',          (0, 0), (-1, -1), 0.4, GREY),
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING',   (0, 0), (-1, -1), 4),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 4),
        ('TOPPADDING',    (0, 1), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 3),
    ]

    current_row = 1
    for cat_key, cat_label, bg_color in EMRG_CAT_LABELS:
        entries = emergency_contacts.get(cat_key, [])
        if not entries:
            continue
        start_row = current_row
        for i, entry in enumerate(entries):
            data.append([
                _wrap(cat_label if i == 0 else '', cat_style),
                _wrap(entry.get('nombre', ''), cell_style),
                _wrap(entry.get('telefono', ''), cell_style),
            ])
            current_row += 1
        end_row = current_row - 1
        if end_row > start_row:
            style_cmds.append(('SPAN',   (0, start_row), (0, end_row)))
            style_cmds.append(('VALIGN', (0, start_row), (0, end_row), 'MIDDLE'))
        style_cmds.append(('BACKGROUND', (0, start_row), (-1, end_row), bg_color))

    if len(data) <= 1:
        return None

    t = Table(data, colWidths=EMRG_COL_WIDTHS, repeatRows=1)
    t.setStyle(TableStyle(style_cmds))
    return t


def _load_state_color(load_state):
    return LIGHT_B if load_state == 'Carga Completa' else colors.HexColor('#fee2e2')


def build_pdf(tramos: list, route_label: str = '') -> bytes:
    """
    Build the full PDF report in memory and return the raw bytes.

    tramos: the list of tramo dicts as returned by segment_route().
            Each tramo must have: posicion_inicial, posicion_final,
            trazo_topografia, distancia_km, risk_analysis,
            emergency_contacts, tramo_coords.
    route_label: optional human-readable route string for the cover page.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        rightMargin=0.4 * inch,
        leftMargin=0.4 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.35 * inch,
    )

    _, cell_style, header_style, caption_style, os_style = _styles()
    story = []

    # ── Cover page ───────────────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.8 * inch))
    story.append(Paragraph(
        'ANÁLISIS DE RIESGOS POR TRAMO DE RUTA',
        ParagraphStyle('Cover', fontName='Helvetica-Bold', fontSize=22, leading=28,
                       textColor=NAVY, spaceAfter=16, alignment=1),
    ))
    story.append(HRFlowable(width='100%', thickness=2, color=PURPLE, spaceAfter=14))
    for label, value in [
        ('Vehículo',           'Camión de doble remolque'),
        ('Dinámica de carga',  'Sale con carga completa · Entrega 50 % en primer destino · Continúa con media carga'),
        ('Ruta',               route_label or 'No especificada'),
        ('Total de tramos',    str(len(tramos))),
        ('Fecha de generación', datetime.now().strftime('%d/%m/%Y %H:%M')),
    ]:
        story.append(Paragraph(
            f'<b>{label}:</b>  {value}',
            ParagraphStyle('MetaLine', fontName='Helvetica', fontSize=11, leading=16,
                           textColor=colors.HexColor('#374151'), spaceBefore=4),
        ))
    story.append(PageBreak())

    # ── Per-tramo pages ─────────────────────────────────────────────────────────────────────
    for tramo in tramos:
        num          = tramo.get('numero', '?')
        pi           = tramo.get('posicion_inicial', {})
        pf           = tramo.get('posicion_final',   {})
        trazo        = tramo.get('trazo_topografia', '')
        dist         = tramo.get('distancia_km', 0)
        ra           = tramo.get('risk_analysis', {})
        tramo_coords = tramo.get('tramo_coords') or []

        load_state    = ra.get('load_state', 'Carga Completa')
        load_flag     = ra.get('load_state_flag', False)
        tabla_proceso = ra.get('tabla_proceso', [])
        os_profile    = ra.get('os_profile', '')

        start_coords = (pi.get('lat', 0), pi.get('lon', 0))
        end_coords   = (pf.get('lat', 0), pf.get('lon', 0))
        seg_label    = f'Tramo {num}'
        lc           = _load_state_color(load_state)

        # ── Segment header band ─────────────────────────────────────────────────────
        header_content = [[
            Paragraph(f'TRAMO {num}', ParagraphStyle(
                'TN', fontName='Helvetica-Bold', fontSize=13, textColor=PURPLE)),
            Paragraph(trazo, ParagraphStyle(
                'TT', fontName='Helvetica', fontSize=10, textColor=colors.HexColor('#374151'))),
            Paragraph(f'Distancia: <b>{dist:.1f} km</b>', ParagraphStyle(
                'TD', fontName='Helvetica', fontSize=9, textColor=colors.HexColor('#374151'))),
            Paragraph(
                f'<b>{load_state}</b>' + (
                    '  ⚠ Perfil modificado por media carga' if load_flag else ''),
                ParagraphStyle('TL', fontName='Helvetica-Bold', fontSize=9,
                               textColor=RED_ACC if load_flag else PURPLE)),
        ]]
        header_table = Table(header_content, colWidths=[1.4*inch, 2.5*inch, 1.7*inch, 3.8*inch])
        header_table.setStyle(TableStyle([
            ('BACKGROUND',   (0, 0), (-1, -1), lc),
            ('BOX',          (0, 0), (-1, -1), 1, PURPLE),
            ('VALIGN',       (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING',  (0, 0), (-1, -1), 8),
            ('TOPPADDING',   (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING',(0, 0), (-1, -1), 7),
        ]))
        story.append(KeepTogether([header_table]))
        story.append(Spacer(1, 0.12 * inch))

        story.append(Paragraph(
            f'Inicio: <b>{pi.get("lat",0):.5f}°N, {pi.get("lon",0):.5f}°O</b>  →  '
            f'Fin: <b>{pf.get("lat",0):.5f}°N, {pf.get("lon",0):.5f}°O</b>',
            ParagraphStyle('Coords', fontName='Helvetica', fontSize=8,
                           textColor=colors.HexColor('#6b7280'), spaceAfter=8),
        ))

        # ── Map image — uses actual route polyline when tramo_coords available ──
        try:
            map_path = get_segment_map(
                start_coords, end_coords, seg_label,
                route_coords=tramo_coords if tramo_coords else None,
            )
            if os.path.exists(map_path) and os.path.getsize(map_path) > 0:
                story.append(Image(map_path, width=6.8 * inch, height=2.8 * inch))
                caption_txt = (
                    f'Mapa del {seg_label} — ruta real trazada en rojo · '
                    'Marcador verde = inicio del tramo · Marcador rojo = fin del tramo'
                    if tramo_coords else
                    f'Mapa del {seg_label} — segmento destacado en rojo · '
                    'Marcador verde = inicio · Marcador rojo = fin'
                )
                story.append(Paragraph(caption_txt, caption_style))
        except Exception as e:
            logger.warning("Map generation failed for tramo %s: %s", num, e)
            story.append(Paragraph(f'[Mapa no disponible para {seg_label}]', caption_style))

        story.append(Spacer(1, 0.1 * inch))

        # ── PROCESO table ──────────────────────────────────────────────────────────────────
        story.append(Paragraph(
            'ANÁLISIS DE RIESGOS OPERATIVOS — PROCESO',
            ParagraphStyle('PH', fontName='Helvetica-Bold', fontSize=9,
                           textColor=NAVY, spaceAfter=5),
        ))
        if tabla_proceso:
            story.append(_build_proceso_table(tabla_proceso, cell_style, header_style))
        else:
            story.append(Paragraph('(Sin datos de análisis disponibles)', caption_style))

        story.append(Spacer(1, 0.1 * inch))

        # ── OS Profile ────────────────────────────────────────────────────────────────────
        story.append(HRFlowable(width='100%', thickness=0.8, color=PURPLE, spaceAfter=6))
        story.append(Paragraph(
            'PERFIL DEL OFICIAL DE SEGURIDAD (OS):',
            ParagraphStyle('OSH', fontName='Helvetica-Bold', fontSize=8,
                           textColor=PURPLE, spaceAfter=3),
        ))
        story.append(Paragraph(os_profile, os_style))

        # ── Emergency contacts table ───────────────────────────────────────────────────
        emergency_contacts = tramo.get('emergency_contacts') or {}
        if emergency_contacts:
            story.append(Spacer(1, 0.12 * inch))
            story.append(HRFlowable(width='100%', thickness=0.8, color=EMRG_RED, spaceAfter=6))
            estado = emergency_contacts.get('estado', '')
            story.append(Paragraph(
                f'CONTACTOS DE EMERGENCIA{" — " + estado.upper() if estado else ""}:',
                ParagraphStyle('EmrgH', fontName='Helvetica-Bold', fontSize=8,
                               textColor=EMRG_RED, spaceAfter=4),
            ))
            emrg_table = _build_emergency_table(emergency_contacts, cell_style)
            if emrg_table:
                story.append(emrg_table)

        story.append(PageBreak())

    doc.build(story)
    return buffer.getvalue()
