"""
PowerPoint report generator — Resumen por Estado.
Widescreen 16:9 (13.33" × 7.5"), one slide per state:
  title slide → overview map slide → per-state slides
    (header + segment map + PROCESO 3-col + emergency contacts).
Uses python-pptx. Map images generated by map_generator.get_segment_map().
"""

import io
import os
import logging
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

from producto.map_generator import get_segment_map
from producto.pdf_generator_summary import _group_by_state, _merge_group
from producto.pptx_generator import (
    _rect, _textbox, _table, _emergency_strip,
    BLUE_DARK, BLUE, RED_DARK, WHITE, GREY_TEXT, DARK_TEXT,
    SLIDE_W, SLIDE_H,
)

logger = logging.getLogger(__name__)


def build_summary_pptx(tramos: list, route_label: str = '') -> bytes:
    """
    Build a summarized PowerPoint grouped by state and return raw bytes.
    tramos: list of tramo dicts as returned by segment_route().
    """
    prs = Presentation()
    prs.slide_width  = SLIDE_W
    prs.slide_height = SLIDE_H
    blank = prs.slide_layouts[6]

    groups = _group_by_state(tramos)
    merged = [_merge_group(g) for g in groups]
    total_dist = round(sum(m['distancia_km'] for m in merged), 2)

    # ── Title slide ────────────────────────────────────────────────────────────
    sl = prs.slides.add_slide(blank)
    _rect(sl, Inches(0), Inches(0), SLIDE_W, SLIDE_H, RGBColor(0xF0, 0xF4, 0xF8))
    _rect(sl, Inches(0), Inches(0),    SLIDE_W, Inches(0.18), BLUE)
    _rect(sl, Inches(0), Inches(7.32), SLIDE_W, Inches(0.18), BLUE)

    _textbox(sl, Inches(1), Inches(1.5), Inches(11.33), Inches(1.2),
             'ANÁLISIS DE RIESGOS — RESUMEN POR ESTADO',
             font_size=26, bold=True, color=BLUE_DARK, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(2.9), Inches(11.33), Inches(0.55),
             route_label or 'Análisis de Ruta',
             font_size=16, color=DARK_TEXT, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(3.65), Inches(11.33), Inches(0.4),
             f'Estados en ruta: {len(merged)}  ·  Distancia total: {total_dist} km',
             font_size=12, color=GREY_TEXT, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(4.2), Inches(11.33), Inches(0.4),
             f'Total de tramos: {len(tramos)}  ·  Fecha: {datetime.now().strftime("%d/%m/%Y %H:%M")}',
             font_size=12, color=GREY_TEXT, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(4.75), Inches(11.33), Inches(0.4),
             'Vehículo: Camión de doble remolque',
             font_size=12, color=GREY_TEXT, align=PP_ALIGN.CENTER)

    # ── Overview map slide ─────────────────────────────────────────────────────
    if tramos:
        all_coords = []
        for i, t in enumerate(tramos):
            coords = t.get('tramo_coords') or []
            all_coords.extend(coords if i == 0 else coords[1:])

        sl = prs.slides.add_slide(blank)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, SLIDE_H, RGBColor(0xF9, 0xFA, 0xFB))

        TITLE_H = Inches(0.60)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, TITLE_H, BLUE_DARK)
        _textbox(sl, Inches(0.2), Inches(0), SLIDE_W - Inches(0.4), TITLE_H,
                 'MAPA GENERAL DE LA RUTA', font_size=16, bold=True, color=WHITE,
                 align=PP_ALIGN.CENTER)

        first = tramos[0].get('posicion_inicial', {})
        last  = tramos[-1].get('posicion_final',  {})
        start = (first.get('lat', 0), first.get('lon', 0))
        end   = (last.get('lat',  0), last.get('lon',  0))
        try:
            mp = get_segment_map(start, end, 'Ruta Completa',
                                 route_coords=all_coords or None)
            if os.path.exists(mp) and os.path.getsize(mp) > 0:
                MAP_W = Inches(11.0)
                MAP_H = Inches(5.8)
                sl.shapes.add_picture(
                    mp,
                    (SLIDE_W - MAP_W) // 2,
                    TITLE_H + Inches(0.15),
                    MAP_W, MAP_H,
                )
        except Exception as e:
            logger.warning("Overview map failed: %s", e)
            _textbox(sl, Inches(1), TITLE_H + Inches(0.3), Inches(11), Inches(2),
                     '[Mapa general no disponible]', font_size=12, color=GREY_TEXT,
                     align=PP_ALIGN.CENTER)

    # ── Per-state slides ───────────────────────────────────────────────────────
    for m in merged:
        state       = m['state']
        pi          = m['posicion_inicial']
        pf          = m['posicion_final']
        trazo       = m['trazo_topografia']
        dist        = m['distancia_km']
        tramo_count = m['tramo_count']
        load_state  = m['load_state']
        summary_rows= m['summary_rows']
        tramo_coords= m.get('tramo_coords') or []
        ec          = m['emergency_contacts']
        is_half     = 'media' in load_state.lower()

        sl = prs.slides.add_slide(blank)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, SLIDE_H, RGBColor(0xF9, 0xFA, 0xFB))

        # Title bar
        TITLE_H = Inches(0.60)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, TITLE_H, BLUE_DARK)
        plural = 's' if tramo_count != 1 else ''
        _textbox(sl, Inches(0.15), Inches(0), Inches(7), TITLE_H,
                 state.upper(), font_size=14, bold=True, color=WHITE)
        _textbox(sl, Inches(7.2), Inches(0), Inches(3.5), TITLE_H,
                 f'Distancia: {dist:.1f} km  ·  {tramo_count} tramo{plural}',
                 font_size=11, color=WHITE)
        _textbox(sl, Inches(11.0), Inches(0), Inches(2.2), TITLE_H,
                 load_state, font_size=10, bold=True,
                 color=RGBColor(0xef, 0x44, 0x44) if is_half else WHITE)

        MAP_TOP = TITLE_H + Inches(0.1)
        MAP_H   = Inches(3.7)
        MAP_W   = Inches(6.1)

        # Segment map
        start_c = (pi.get('lat', 0), pi.get('lon', 0))
        end_c   = (pf.get('lat', 0), pf.get('lon', 0))
        try:
            mp = get_segment_map(start_c, end_c, state,
                                 route_coords=tramo_coords or None)
            if os.path.exists(mp) and os.path.getsize(mp) > 0:
                sl.shapes.add_picture(mp, Inches(0.1), MAP_TOP, MAP_W, MAP_H)
        except Exception as e:
            logger.warning("Map failed for state %s: %s", state, e)
            _textbox(sl, Inches(0.1), MAP_TOP, MAP_W, MAP_H,
                     '[Mapa no disponible]', font_size=10, color=GREY_TEXT)

        # Coordinates below map
        _textbox(
            sl, Inches(0.1), MAP_TOP + MAP_H + Inches(0.05), MAP_W, Inches(0.35),
            f'Inicio: {pi.get("lat",0):.5f}°N, {pi.get("lon",0):.5f}°O  →  '
            f'Fin: {pf.get("lat",0):.5f}°N, {pf.get("lon",0):.5f}°O',
            font_size=7, color=GREY_TEXT,
        )

        # Right column — PROCESO summary
        RIGHT_L = MAP_W + Inches(0.3)
        RIGHT_W = SLIDE_W - RIGHT_L - Inches(0.1)
        _textbox(sl, RIGHT_L, MAP_TOP, RIGHT_W, Inches(0.3),
                 'RESUMEN DE RIESGOS — PROCESO',
                 font_size=9, bold=True, color=BLUE_DARK)

        if summary_rows:
            _table(sl, RIGHT_L, MAP_TOP + Inches(0.32), RIGHT_W, summary_rows)

        # Emergency strip
        EMRG_TOP = Inches(5.42)
        _emergency_strip(sl, ec, EMRG_TOP)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
