"""
PowerPoint report generator — Análisis de Riesgos por Tramo de Ruta.
Widescreen 16:9 (13.33" × 7.5"), one slide per tramo:
  title slide → per-tramo slides (header + map + PROCESO 3-col + emergency strip).
Uses python-pptx. Map images generated by map_generator.get_segment_map().
"""

import io
import os
import logging
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

from producto.map_generator import get_segment_map

logger = logging.getLogger(__name__)

# ── Palette — mirrors pdf_generator.py red/blue scheme ───────────────────────
BLUE_DARK  = RGBColor(0x1e, 0x40, 0xaf)
BLUE       = RGBColor(0x25, 0x63, 0xeb)
RED        = RGBColor(0xef, 0x44, 0x44)
RED_DARK   = RGBColor(0xdc, 0x26, 0x26)
WHITE      = RGBColor(0xFF, 0xFF, 0xFF)
GREY_TEXT  = RGBColor(0x6b, 0x72, 0x80)
DARK_TEXT  = RGBColor(0x37, 0x41, 0x51)
STRIPE_BG  = RGBColor(0xf0, 0xf4, 0xf8)
LIGHT_BLUE = RGBColor(0xdb, 0xea, 0xfe)

SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)


# ─────────────────────────────────────────────────────────────────────────────
# Low-level shape helpers
# ─────────────────────────────────────────────────────────────────────────────

def _rect(slide, left, top, width, height, fill_rgb):
    from pptx.enum.shapes import MSO_SHAPE_TYPE
    shape = slide.shapes.add_shape(1, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_rgb
    shape.line.color.rgb = fill_rgb
    return shape


def _textbox(slide, left, top, width, height, text,
             font_size=11, bold=False, italic=False,
             color=None, align=PP_ALIGN.LEFT, word_wrap=True):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = word_wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    if color:
        run.font.color.rgb = color
    return txBox


def _table(slide, left, top, width, rows_data):
    """
    Add a 3-column table (Área / Nivel de Riesgo / Intervención).
    rows_data: list of [area, nivel, intervencion] strings.
    """
    n_data = len(rows_data)
    if n_data == 0:
        return

    row_h   = Inches(0.27)
    hdr_h   = Inches(0.28)
    total_h = hdr_h + row_h * n_data

    col_w = [int(width * 0.18), int(width * 0.50), width - int(width * 0.18) - int(width * 0.50)]

    tbl = slide.shapes.add_table(n_data + 1, 3, left, top, width, total_h).table
    for i, w in enumerate(col_w):
        tbl.columns[i].width = w

    # Header row
    for ci, hdr in enumerate(['Área', 'Nivel de Riesgo', 'Intervención']):
        cell = tbl.cell(0, ci)
        cell.fill.solid()
        cell.fill.fore_color.rgb = BLUE_DARK
        tf = cell.text_frame
        tf.paragraphs[0].text = hdr
        run = tf.paragraphs[0].runs[0]
        run.font.bold = True
        run.font.size = Pt(7)
        run.font.color.rgb = WHITE

    # Data rows
    for ri, row in enumerate(rows_data, start=1):
        bg = STRIPE_BG if ri % 2 == 0 else WHITE
        for ci, val in enumerate(row):
            cell = tbl.cell(ri, ci)
            cell.fill.solid()
            cell.fill.fore_color.rgb = bg
            tf = cell.text_frame
            tf.word_wrap = True
            tf.paragraphs[0].text = str(val)
            if tf.paragraphs[0].runs:
                tf.paragraphs[0].runs[0].font.size = Pt(6.5)


def _get_summary_rows(tabla_proceso: list) -> list:
    """Collapse 7-col PROCESO rows to [Área, Vigilancia, Intervención]."""
    return [
        [r[1] if len(r) > 1 else '',
         r[4] if len(r) > 4 else '',
         r[6] if len(r) > 6 else '']
        for r in (tabla_proceso or [])
    ]


def _emergency_strip(slide, ec: dict, top):
    """Compact emergency strip: colored header bar + 4 contact columns."""
    if not ec:
        return

    hdr_h  = Inches(0.30)
    body_h = Inches(1.65)
    estado = ec.get('estado', '')

    _rect(slide, Inches(0), top, SLIDE_W, hdr_h, RED_DARK)
    _textbox(
        slide, Inches(0.15), top, SLIDE_W - Inches(0.3), hdr_h,
        f'CONTACTOS DE EMERGENCIA{" — " + estado.upper() if estado else ""}',
        font_size=8, bold=True, color=WHITE,
    )

    cats = [
        ('ambulancia',       'Ambulancia / Cruz Roja', RGBColor(0xFF, 0xF1, 0xF2)),
        ('guardia_nacional',  'Guardia Nacional',       RGBColor(0xF0, 0xFD, 0xF4)),
        ('guardia_caminos',   'GN Carreteras / CAPUFE', RGBColor(0xF0, 0xFD, 0xFA)),
        ('policia_estatal',   'Policía Estatal (SSP)',  RGBColor(0xFA, 0xF5, 0xFF)),
    ]
    col_w = SLIDE_W // len(cats)
    body_top = top + hdr_h

    for i, (key, label, bg) in enumerate(cats):
        entries = ec.get(key, [])
        _rect(slide, col_w * i, body_top, col_w, body_h, bg)
        lines = [label]
        for e in entries[:2]:
            nombre  = e.get('nombre',   '')
            telefono= e.get('telefono', '')
            lines.append(f'{nombre}  {telefono}')
        _textbox(
            slide, col_w * i + Inches(0.08), body_top + Inches(0.05),
            col_w - Inches(0.1), body_h - Inches(0.05),
            '\n'.join(lines), font_size=7, bold=False, color=DARK_TEXT,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def build_pptx(tramos: list, route_label: str = '') -> bytes:
    """
    Build a detailed PowerPoint (one slide per tramo) and return raw bytes.
    tramos: list of tramo dicts as returned by segment_route().
    """
    prs = Presentation()
    prs.slide_width  = SLIDE_W
    prs.slide_height = SLIDE_H
    blank = prs.slide_layouts[6]

    # ── Title slide ────────────────────────────────────────────────────────────
    sl = prs.slides.add_slide(blank)
    _rect(sl, Inches(0), Inches(0), SLIDE_W, SLIDE_H, RGBColor(0xF0, 0xF4, 0xF8))
    _rect(sl, Inches(0), Inches(0),     SLIDE_W, Inches(0.18), BLUE)
    _rect(sl, Inches(0), Inches(7.32),  SLIDE_W, Inches(0.18), BLUE)
    _textbox(sl, Inches(1), Inches(1.6), Inches(11.33), Inches(1.2),
             'ANÁLISIS DE RIESGOS POR TRAMO DE RUTA',
             font_size=26, bold=True, color=BLUE_DARK, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(3.0), Inches(11.33), Inches(0.55),
             route_label or 'Análisis de Ruta',
             font_size=16, color=DARK_TEXT, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(3.75), Inches(11.33), Inches(0.4),
             f'Total de tramos: {len(tramos)}  ·  Fecha: {datetime.now().strftime("%d/%m/%Y %H:%M")}',
             font_size=12, color=GREY_TEXT, align=PP_ALIGN.CENTER)
    _textbox(sl, Inches(1), Inches(4.3), Inches(11.33), Inches(0.4),
             'Vehículo: Camión de doble remolque',
             font_size=12, color=GREY_TEXT, align=PP_ALIGN.CENTER)

    # ── Per-tramo slides ───────────────────────────────────────────────────────
    for tramo in tramos:
        sl = prs.slides.add_slide(blank)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, SLIDE_H, RGBColor(0xF9, 0xFA, 0xFB))

        num   = tramo.get('numero', '?')
        trazo = tramo.get('trazo_topografia', '')
        dist  = tramo.get('distancia_km', 0)
        ra    = tramo.get('risk_analysis', {})
        pi    = tramo.get('posicion_inicial', {})
        pf    = tramo.get('posicion_final',   {})
        load_state   = ra.get('load_state', 'Carga Completa')
        tabla_proceso= ra.get('tabla_proceso', [])
        tramo_coords = tramo.get('tramo_coords') or []
        is_half      = 'media' in load_state.lower()

        # Title bar
        TITLE_H = Inches(0.60)
        _rect(sl, Inches(0), Inches(0), SLIDE_W, TITLE_H, BLUE_DARK)
        _textbox(sl, Inches(0.15), Inches(0), Inches(6), TITLE_H,
                 f'TRAMO {num}  —  {trazo}', font_size=14, bold=True, color=WHITE)
        _textbox(sl, Inches(6.5), Inches(0), Inches(3.5), TITLE_H,
                 f'Distancia: {dist:.1f} km', font_size=12, color=WHITE)
        _textbox(sl, Inches(10.2), Inches(0), Inches(3.0), TITLE_H,
                 load_state, font_size=11, bold=True,
                 color=RED if is_half else WHITE)

        # Map — left column
        MAP_TOP = TITLE_H + Inches(0.1)
        MAP_H   = Inches(3.7)
        MAP_W   = Inches(6.1)
        start_c = (pi.get('lat', 0), pi.get('lon', 0))
        end_c   = (pf.get('lat', 0), pf.get('lon', 0))
        try:
            mp = get_segment_map(start_c, end_c, f'Tramo {num}',
                                 route_coords=tramo_coords or None)
            if os.path.exists(mp) and os.path.getsize(mp) > 0:
                sl.shapes.add_picture(mp, Inches(0.1), MAP_TOP, MAP_W, MAP_H)
        except Exception as e:
            logger.warning("Map failed for tramo %s: %s", num, e)
            _textbox(sl, Inches(0.1), MAP_TOP, MAP_W, MAP_H,
                     '[Mapa no disponible]', font_size=10, color=GREY_TEXT)

        # Coordinates below map
        _textbox(
            sl, Inches(0.1), MAP_TOP + MAP_H + Inches(0.05), MAP_W, Inches(0.35),
            f'Inicio: {pi.get("lat",0):.5f}°N, {pi.get("lon",0):.5f}°O  →  '
            f'Fin: {pf.get("lat",0):.5f}°N, {pf.get("lon",0):.5f}°O',
            font_size=7, color=GREY_TEXT,
        )

        # Right column — PROCESO summary
        RIGHT_L = MAP_W + Inches(0.3)
        RIGHT_W = SLIDE_W - RIGHT_L - Inches(0.1)
        _textbox(sl, RIGHT_L, MAP_TOP, RIGHT_W, Inches(0.3),
                 'RESUMEN DE RIESGOS — PROCESO',
                 font_size=9, bold=True, color=BLUE_DARK)

        summary_rows = _get_summary_rows(tabla_proceso)
        if summary_rows:
            _table(sl, RIGHT_L, MAP_TOP + Inches(0.32), RIGHT_W, summary_rows)

        # Emergency strip
        EMRG_TOP = Inches(5.42)
        _emergency_strip(sl, tramo.get('emergency_contacts') or {}, EMRG_TOP)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
