import math
from typing import Dict, List, Optional

from producto.risk_analysis import generate_risk_analysis, FULL_LOAD, HALF_LOAD

TRAZO_RECTA = 'Recta'
TRAZO_RECTA_ASCENDENTE = 'Recta Ascendente'
TRAZO_RECTA_DESCENDENTE = 'Recta Descendente'
TRAZO_CURVA_ASCENDENTE = 'Curva Ascendente'
TRAZO_CURVA_DESCENDENTE = 'Curva Descendente'

# Bearing-change threshold (degrees, after smoothing) that signals a curve.
# Raised to 10° because sample coordinates are spaced ~40 km apart — at that
# density even gently curving highways produce bearing changes > 3°.
BEARING_CURVE_THRESHOLD = 10.0
# Smoothing window size (segments) for both curvature and grade signals
SMOOTHING_WINDOW = 5
# Minimum Tramo length; prevents micro-segments from over-segmentation
MIN_TRAMO_DISTANCE_M = 500.0
# Grade fraction (rise/run) that classifies a segment as ascending/descending.
# Lowered to 0.3 % so gentle plateau grades are still captured.
GRADE_THRESHOLD = 0.003
# Maximum distance (metres) a reference may be from the nearest route coordinate
# before it is discarded.  25 km is generous enough to handle the 35 km sample
# spacing (worst-case a reference between two samples sits ~17 km from the
# nearest sampled point) while still excluding references on unrelated corridors.
MAX_REF_DISTANCE_M = 25_000.0
# Minimum monitoring checkpoints per tramo — filled with Punto de control markers
# generated by interpolating along the route geometry so they carry real coordinates.
MIN_REFS_PER_TRAMO = 30


def _haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6_371_000.0
    rad = math.pi / 180.0
    dlat = (lat2 - lat1) * rad
    dlon = (lon2 - lon1) * rad
    a = (math.sin(dlat / 2) ** 2
         + math.cos(lat1 * rad) * math.cos(lat2 * rad) * math.sin(dlon / 2) ** 2)
    return R * 2.0 * math.atan2(math.sqrt(a), math.sqrt(1.0 - a))


def _bearing(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    rad = math.pi / 180.0
    lat1r, lon1r = lat1 * rad, lon1 * rad
    lat2r, lon2r = lat2 * rad, lon2 * rad
    dlon = lon2r - lon1r
    x = math.sin(dlon) * math.cos(lat2r)
    y = math.cos(lat1r) * math.sin(lat2r) - math.sin(lat1r) * math.cos(lat2r) * math.cos(dlon)
    return (math.degrees(math.atan2(x, y)) + 360.0) % 360.0


def _angular_diff(b1: float, b2: float) -> float:
    return (b2 - b1 + 180.0) % 360.0 - 180.0


def _smooth(values: List[float], window: int) -> List[float]:
    half = window // 2
    result = []
    for i in range(len(values)):
        lo = max(0, i - half)
        hi = min(len(values), i + half + 1)
        result.append(sum(values[lo:hi]) / (hi - lo))
    return result


def _interpolate_along_tramo(
    coordinates: List[Dict],
    seg_start: int,
    seg_end: int,
    distances: List[float],
    n_points: int,
) -> List[Dict]:
    """Return n_points evenly-spaced lat/lon dicts along the tramo polyline."""
    if n_points <= 0 or seg_end <= seg_start:
        return []
    total = sum(distances[seg_start:seg_end])
    if total < 1.0:
        return []
    interval = total / (n_points + 1)
    result: List[Dict] = []
    accumulated = 0.0
    next_target = interval
    for i in range(seg_start, seg_end):
        seg_dist = distances[i]
        if seg_dist < 1e-6:
            continue
        while next_target <= accumulated + seg_dist + 1e-6 and len(result) < n_points:
            t = min(1.0, (next_target - accumulated) / seg_dist)
            lat = coordinates[i]['lat'] + t * (coordinates[i + 1]['lat'] - coordinates[i]['lat'])
            lon = coordinates[i]['lon'] + t * (coordinates[i + 1]['lon'] - coordinates[i]['lon'])
            result.append({'lat': round(lat, 6), 'lon': round(lon, 6)})
            next_target += interval
        accumulated += seg_dist
        if len(result) >= n_points:
            break
    return result


def _nearest_segment_idx(coordinates: List[Dict], lat: float, lon: float) -> int:
    min_d = float('inf')
    best = 0
    for i in range(len(coordinates) - 1):
        d = _haversine_m(lat, lon, coordinates[i]['lat'], coordinates[i]['lon'])
        if d < min_d:
            min_d = d
            best = i
    return best



def segment_route(
    coordinates: List[Dict],
    references: Optional[List[Dict]] = None,
    vehicle_config: Optional[Dict] = None,
) -> Dict:
    """
    Segment a route into Tramos for Mexican territory road analysis.

    coordinates:    list of {'lat': float, 'lon': float, 'elevation': float|None}
    references:     list of {'lat': float, 'lon': float,
                              'type': 'caseta'|'paradero'|'rampa', 'name': str}
    vehicle_config: optional dict:
                    {
                      'vehicle_type': 'double_trailer',   # currently only supported type
                      'first_delivery_coord_index': int    # index into coordinates where
                                                           # first delivery occurs; tramos
                                                           # starting before this index are
                                                           # FULL_LOAD, at/after are HALF_LOAD
                    }

    Returns {'tramos': [...], 'total_tramos': int, 'distancia_total_km': float,
             'matched_references': [{'lat', 'lon', 'type', 'name'}, ...]}
    Each tramo includes a 'risk_analysis' block with 6 structured sections.
    """
    if references is None:
        references = []
    if vehicle_config is None:
        vehicle_config = {}

    first_delivery_idx = vehicle_config.get('first_delivery_coord_index')

    n = len(coordinates)
    if n < 2:
        return {
            'tramos': [],
            'total_tramos': 0,
            'distancia_total_km': 0.0,
            'matched_references': [],
        }

    # ── 1. Per-segment bearings and distances ─────────────────────────────────
    bearings: List[float] = []
    distances: List[float] = []
    for i in range(n - 1):
        c1, c2 = coordinates[i], coordinates[i + 1]
        bearings.append(_bearing(c1['lat'], c1['lon'], c2['lat'], c2['lon']))
        distances.append(_haversine_m(c1['lat'], c1['lon'], c2['lat'], c2['lon']))

    # ── 2. Curvature signal: absolute bearing change between segments ──────
    bearing_changes: List[float] = [0.0]
    for i in range(1, len(bearings)):
        bearing_changes.append(abs(_angular_diff(bearings[i - 1], bearings[i])))
    smoothed_curve = _smooth(bearing_changes, SMOOTHING_WINDOW)

    # ── 3. Elevation grade ─────────────────────────────────────────────
    has_elevation = any(c.get('elevation') is not None for c in coordinates)
    grades: List[float] = []
    for i in range(n - 1):
        if has_elevation and distances[i] > 0.0:
            e1 = float(coordinates[i].get('elevation') or 0.0)
            e2 = float(coordinates[i + 1].get('elevation') or 0.0)
            grades.append((e2 - e1) / distances[i])
        else:
            grades.append(0.0)
    smoothed_grade = _smooth(grades, SMOOTHING_WINDOW)

    # ── 4. Per-segment classification ─────────────────────────────────────
    def _classify(curve_val: float, grade_val: float) -> str:
        is_curve = curve_val > BEARING_CURVE_THRESHOLD
        is_ascending = grade_val > GRADE_THRESHOLD
        is_descending = grade_val < -GRADE_THRESHOLD

        if is_curve:
            return TRAZO_CURVA_DESCENDENTE if is_descending else TRAZO_CURVA_ASCENDENTE
        else:
            if is_ascending:
                return TRAZO_RECTA_ASCENDENTE
            if is_descending:
                return TRAZO_RECTA_DESCENDENTE
            return TRAZO_RECTA

    classifications = [
        _classify(smoothed_curve[i], smoothed_grade[i])
        for i in range(len(bearings))
    ]

    # ── 5. Map references to nearest segment indices ──────────────────────
    ref_by_seg: Dict[int, List[Dict]] = {}
    caseta_segs: set = set()
    matched_ref_objects: List[Dict] = []

    for ref in references:
        # Only include references within MAX_REF_DISTANCE_M of the route.
        # Without this check every reference sent by the client is blindly
        # assigned to some tramo even if it is hundreds of km away.
        min_d = min(
            _haversine_m(ref['lat'], ref['lon'], c['lat'], c['lon'])
            for c in coordinates
        )
        if min_d > MAX_REF_DISTANCE_M:
            continue

        idx = _nearest_segment_idx(coordinates, ref['lat'], ref['lon'])
        ref_by_seg.setdefault(idx, []).append(ref)
        if ref.get('type') == 'caseta':
            caseta_segs.add(idx)
        matched_ref_objects.append({
            'lat': ref['lat'],
            'lon': ref['lon'],
            'type': ref.get('type', ''),
            'name': ref.get('name', ''),
        })

    # ── 6. Tramo boundaries ───────────────────────────────────────────────
    # A boundary is placed when:
    #   a) classification changes AND accumulated distance >= MIN_TRAMO_DISTANCE_M
    #   b) a caseta falls on the segment (toll booths always split a Tramo)
    boundaries = [0]
    dist_since_last = 0.0
    for i in range(1, len(classifications)):
        dist_since_last += distances[i - 1]
        is_caseta = i in caseta_segs
        is_change = classifications[i] != classifications[i - 1]
        if (is_change or is_caseta) and dist_since_last >= MIN_TRAMO_DISTANCE_M:
            boundaries.append(i)
            dist_since_last = 0.0
    boundaries.append(n - 1)

    # ── 7. Build Tramo objects ────────────────────────────────────────────
    tramos: List[Dict] = []
    prev_caseta_names: List[str] = []

    for t in range(len(boundaries) - 1):
        seg_start = boundaries[t]
        seg_end = boundaries[t + 1]

        seg_classes = classifications[seg_start:seg_end]
        dominant = (
            max(set(seg_classes), key=seg_classes.count)
            if seg_classes else TRAZO_RECTA
        )

        dist_m = sum(distances[seg_start:seg_end])

        referencias: List[str] = []
        caseta_names_here: List[str] = []

        for seg_idx in range(seg_start, seg_end):
            for ref in ref_by_seg.get(seg_idx, []):
                dist_from_start_km = sum(distances[seg_start:seg_idx]) / 1000.0
                rtype = ref.get('type', '')
                rname = ref.get('name', 'Punto de referencia')
                km_str = f"{dist_from_start_km:.1f} km del inicio del tramo"
                if rtype == 'caseta':
                    referencias.append(f"Caseta de cobro: {rname} a {km_str}")
                    caseta_names_here.append(rname)
                elif rtype == 'paradero':
                    referencias.append(f"Paradero: {rname} a {km_str}")
                elif rtype == 'gasolinera':
                    referencias.append(f"Gasolinera: {rname} a {km_str}")
                elif rtype == 'rampa':
                    referencias.append(
                        f"Rampa de emergencia: {rname} a {km_str}"
                    )

        for cname in prev_caseta_names:
            referencias.insert(0, f"Viene de Caseta: {cname}")

        # ── Monitoring checkpoints — guarantee MIN_REFS_PER_TRAMO entries ────────
        # Interpolated from the sampled route geometry so every checkpoint carries
        # a real lat/lon that appears on the map as a tracking marker.
        needed = max(0, MIN_REFS_PER_TRAMO - len(referencias))
        if needed > 0:
            tramo_start_km = sum(distances[:seg_start]) / 1000.0
            cp_spacing_km = (dist_m / 1000.0) / (needed + 1)
            checkpoints = _interpolate_along_tramo(
                coordinates, seg_start, seg_end, distances, needed
            )
            for j, cp in enumerate(checkpoints):
                cp_km = round(tramo_start_km + (j + 1) * cp_spacing_km, 1)
                cp_name = f'Punto de control km {cp_km}'
                referencias.append(f'Seguimiento: {cp_name}')
                matched_ref_objects.append({
                    'lat': cp['lat'],
                    'lon': cp['lon'],
                    'type': 'seguimiento',
                    'name': cp_name,
                })

        # Determine load state for this tramo based on vehicle_config
        if first_delivery_idx is not None and seg_start >= first_delivery_idx:
            load_state = HALF_LOAD
        else:
            load_state = FULL_LOAD

        tramo_dict = {
            'numero': t + 1,
            'posicion_inicial': {
                'lat': round(coordinates[seg_start]['lat'], 6),
                'lon': round(coordinates[seg_start]['lon'], 6),
            },
            'posicion_final': {
                'lat': round(coordinates[seg_end]['lat'], 6),
                'lon': round(coordinates[seg_end]['lon'], 6),
            },
            'trazo_topografia': dominant,
            'referencias': referencias,
            'distancia_km': round(dist_m / 1000.0, 2),
        }

        tramo_dict['risk_analysis'] = generate_risk_analysis(tramo_dict, load_state)
        tramos.append(tramo_dict)

        prev_caseta_names = caseta_names_here

    return {
        'tramos': tramos,
        'total_tramos': len(tramos),
        'distancia_total_km': round(sum(distances) / 1000.0, 2),
        'matched_references': matched_ref_objects,
    }
